name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          [
            { node: "16.13", typeorm: "0.3.20" },
            { node: "17", typeorm: "0.3.20" },
            { node: "18", typeorm: "0.3.20" },
            { node: "19", typeorm: "0.3.20" },
            { node: "20", typeorm: "0.3.20" },
            { node: "21", typeorm: "0.3.20" },
          ]

    name: Node ${{ matrix.config.node }}, TypeORM ${{ matrix.config.typeorm }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.config.node }}

      - name: Install TypeORM
        run: npm install typeorm@${{ matrix.config.typeorm }}

      - name: Run tests
        run: npm run test:e2e
